return {
    protocol = 3,
    sim_paused = false,
    prefix = "DST_OTEL|",
    max_line_bytes = 64 * 1024,
    installed = false,
    requested_profile = "off",
    last_error = nil,
    telemetry_active = false,
    nonce = nil,
    generation = nil,
    sequence = 0,
    errors = 0,
    outdated_mods = {},
    health_revision = 0,
    faults = {},
    capabilities = {},
    action_allowlist = {},
    players = setmetatable({}, { __mode = "k" }),
}
