import builtins
from collections.abc import Awaitable, Sequence
from os import PathLike
from pathlib import Path
from typing import Any, Literal

class DstError(Exception):
    code: str
    details: Any

class Client:
    @staticmethod
    def connect(path: str | PathLike[str]) -> Awaitable[Client]: ...
    def call(
        self,
        method: str,
        arguments: dict[str, Any] | None = None,
        *,
        shard: str | None = None,
        timeout: float | None = None,
    ) -> Awaitable[Any]: ...
    def describe(self) -> Awaitable[dict[str, Any]]: ...
    def subscribe(
        self, kind: Literal["logs", "lifecycle", "events"]
    ) -> Awaitable[Subscription]: ...
    def close(self) -> Awaitable[None]: ...

class Subscription:
    def next(self, max_items: int = 512) -> Awaitable[dict[str, Any]]: ...
    def close(self) -> Awaitable[None]: ...

def describe(scope: Literal["room", "shard"] = "room") -> list[dict[str, Any]]: ...
def inspect(directory: str | PathLike[str]) -> dict[str, Any]: ...
def run_cli(arguments: list[str]) -> int: ...

class Configuration:
    def __init__(
        self, model: str, values: dict[str, Any] | None = None, **fields: Any
    ) -> None: ...
    @property
    def model(self) -> str: ...
    def dump(
        self, *, defaults: bool = False, secrets: bool = False
    ) -> dict[str, Any]: ...
    def schema(self) -> dict[str, Any]: ...
    def replace(self, **changes: Any) -> Configuration: ...
    @staticmethod
    def parse(model: str, source: str, *, kind: str | None = None) -> Configuration: ...
    @staticmethod
    def load(
        directory: str | PathLike[str],
        *,
        world_kinds: dict[str, str] | None = None,
        level_kinds: dict[str, str] | None = None,
    ) -> Configuration: ...
    def render(self, *, multi_shard: bool = False) -> str: ...
    def files(self) -> dict[str, str]: ...
    def save(
        self, directory: str | PathLike[str], *, replace_permissions: bool = False
    ) -> list[Path]: ...
    @staticmethod
    def compose(parts: Sequence[Configuration]) -> Configuration: ...
    def build(
        self,
        *,
        token: str = "",
        cluster_key: str | None = None,
        settings: Configuration | dict[str, Any] | None = None,
    ) -> Configuration: ...

class Room:
    def __init__(self, value: dict[str, Any] | None = None, **fields: Any) -> None: ...
    @property
    def number(self) -> int: ...
    @property
    def cluster(self) -> Configuration: ...
    def dump(
        self, *, defaults: bool = False, secrets: bool = False
    ) -> dict[str, Any]: ...
    @staticmethod
    def schema() -> dict[str, Any]: ...
    def get(self, pointer: str = "") -> Any: ...
    def edit(self, pointer: str, value: Any = None, *, unset: bool = False) -> Room: ...
    def edit_many(
        self,
        changes: Sequence[tuple[str, Any]] | None = None,
        *,
        unset: Sequence[str] | None = None,
    ) -> Room: ...

class RoomStore:
    def __init__(
        self,
        root: str | PathLike[str],
        *,
        quadlet_dir: str | PathLike[str] | None = None,
    ) -> None: ...
    @property
    def root(self) -> Path: ...
    def path(self, room_number: int) -> Path: ...
    def numbers(self) -> builtins.list[int]: ...
    def load(self, room_number: int) -> Room: ...
    def list(self) -> builtins.list[Room]: ...
    def save(self, room: Room) -> builtins.list[Path]: ...
    def save_policy(self, room: Room) -> None: ...

def configuration_schema(model: str) -> dict[str, Any]: ...
def template_names() -> list[str]: ...
def preset_names() -> list[str]: ...
def preset(name: str) -> Configuration: ...
def room_numbers() -> list[int]: ...
def build_template(
    name: str,
    *,
    number: int | None = None,
    token: str = "",
    cluster_key: str | None = None,
    settings: Configuration | dict[str, Any] | None = None,
) -> Configuration: ...
def fleet_room(
    room_number: int, *, token: str = "", cluster_key: str | None = None
) -> Room: ...
def room_name(room_number: int) -> str: ...
def room_schedule(room_number: int) -> tuple[str, int, int] | None: ...
def build_bundle(
    source: str | PathLike[str], output: str | PathLike[str]
) -> dict[str, Any]: ...
def verify_bundle(
    path: str | PathLike[str], *, source: str | PathLike[str] | None = None
) -> dict[str, Any]: ...
def generate_components(directory: str | PathLike[str]) -> str: ...
def generate_modutil(path: str | PathLike[str]) -> str: ...
def parse_component(
    source: str, filename: str, class_name: str, folder_name: str
) -> tuple[list[str], list[str]]: ...
def parse_modutil(source: str, filename: str) -> list[str]: ...
def parse_lua_literal(source: str) -> Any: ...
def parse_lua_return_table(source: str) -> dict[str, Any]: ...
def render_lua_literal(value: Any) -> str: ...

class Host:
    def __init__(
        self,
        root: str | PathLike[str],
        quadlet_dir: str | PathLike[str],
        *,
        systemctl: str | PathLike[str] | None = None,
        journalctl: str | PathLike[str] | None = None,
        user: bool = False,
        command_timeout: float = 30.0,
        port_start: int = 30000,
        port_end: int = 65535,
    ) -> None: ...
    @property
    def rooms(self) -> RoomStore: ...
    def units(self, number: int) -> builtins.list[str]: ...
    def list(self) -> Awaitable[builtins.list[dict[str, Any]]]: ...
    def load(self, number: int) -> Awaitable[Room]: ...
    def create(self, definition: Room) -> Awaitable[Room]: ...
    def edit(self, definition: Room) -> Awaitable[Room]: ...
    def edit_fields(
        self, number: int, changes: builtins.list[tuple[str, Any]], unset: Sequence[str]
    ) -> Awaitable[Room]: ...
    def operate(self, number: int, request: dict[str, Any]) -> Awaitable[Any]: ...
    def batch(
        self, numbers: Sequence[int], request: dict[str, Any]
    ) -> Awaitable[builtins.list[dict[str, Any]]]: ...
    def provision(
        self, definitions: Sequence[Room]
    ) -> Awaitable[builtins.list[dict[str, Any]]]: ...
    def connect(self, number: int) -> Awaitable[Client]: ...
    def journal(
        self, numbers: Sequence[int], request: dict[str, Any]
    ) -> Awaitable[dict[str, Any]]: ...
    def follow_journal(
        self, numbers: Sequence[int], request: dict[str, Any]
    ) -> Awaitable[JournalStream]: ...

class KleiClient:
    def __init__(
        self,
        access_token: str | None = None,
        *,
        endpoints: dict[str, str] | None = None,
        request_timeout: float = 30.0,
        connect_timeout: float = 10.0,
        max_response_bytes: int = 33_554_432,
        lobby_concurrency: int = 8,
        room_concurrency: int = 24,
    ) -> None: ...
    def get_latest_build(self, version_type: str = "release") -> Awaitable[int]: ...
    def get_versions(self) -> Awaitable[list[dict[str, Any]]]: ...
    def get_regions(self) -> Awaitable[list[str]]: ...
    def lobby(
        self, region: str, platform: str = "Steam"
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def room(self, row_id: str, region: str) -> Awaitable[dict[str, Any] | None]: ...
    def get_lobbies(
        self,
        regions: Sequence[str] | None = None,
        platforms: Sequence[str] | None = None,
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def get_rooms(
        self, rooms: list[dict[str, Any]]
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def discover_rooms(self) -> Awaitable[dict[str, Any]]: ...

class LogProcessError(RuntimeError):
    command: list[str]
    returncode: int
    diagnostics: str
    diagnostics_truncated: bool

class JournalCursorError(RuntimeError):
    cursor: str

class JournalLogs:
    def __init__(
        self,
        executable: str | PathLike[str],
        max_record_bytes: int,
        max_output_bytes: int,
    ) -> None: ...
    def query(
        self,
        units: Sequence[str] | None,
        request: dict[str, Any],
        completion_timeout: float,
    ) -> Awaitable[dict[str, Any]]: ...
    def follow(
        self, units: Sequence[str] | None, request: dict[str, Any]
    ) -> Awaitable[JournalStream]: ...

class JournalStream:
    @property
    def pid(self) -> int: ...
    @property
    def diagnostics(self) -> str: ...
    @property
    def diagnostics_truncated(self) -> bool: ...
    def next(self) -> Awaitable[dict[str, Any] | None]: ...
    def close(self) -> Awaitable[None]: ...

class NetdataLogs:
    def __init__(
        self,
        executable: str | PathLike[str],
        stock_config: str | PathLike[str],
        config: str | PathLike[str],
        max_concurrency: int,
        max_record_bytes: int,
        max_output_bytes: int,
    ) -> None: ...
    def query(
        self, request: dict[str, Any], completion_timeout: float
    ) -> Awaitable[dict[str, Any]]: ...

def event_schema() -> dict[str, Any]: ...
def validate_event(value: object) -> dict[str, Any]: ...

class ClusterArchive:
    def __init__(self, filename: str, stream: Any) -> None: ...
    @property
    def filename(self) -> str: ...
    @property
    def stream(self) -> Any: ...
    def close(self) -> None: ...
    def save(self, path: str | PathLike[str]) -> Awaitable[None]: ...
    def start_upload(
        self,
        *,
        bucket: str | None = None,
        endpoint: str | None = None,
        region: str | None = None,
        access_key_id: str | None = None,
        secret_access_key: str | None = None,
        session_token: str | None = None,
        object_prefix: str = "",
        url_prefix: str | None = None,
    ) -> ArchiveUpload: ...

class ArchiveUpload:
    def wait(self) -> Awaitable[dict[str, Any]]: ...
    def cancel(self) -> Awaitable[None]: ...

def export_archive(
    host: Host,
    number: int,
    *,
    options: dict[str, Any] | None = None,
    compression_level: int = 3,
) -> Awaitable[ClusterArchive]: ...
