return {
    protocol = 2,
    prefix = "DST_OTEL|",
    max_line_bytes = 64 * 1024,
    installed = false,
    requested_profile = "off",
    last_error = nil,
    telemetry_active = false,
    nonce = nil,
    generation = nil,
    sequence = 0,
    action_sequence = 0,
    current_action = nil,
    errors = 0,
    action_allowlist = {},
    players = setmetatable({}, { __mode = "k" }),
}
