return {
    protocol = 1,
    prefix = "DST_OTEL|",
    max_line_bytes = 64 * 1024,
    installed = false,
    requested_profile = "off",
    telemetry_error = nil,
    telemetry_active = false,
    nonce = nil,
    sequence = 0,
    action_sequence = 0,
    events_emitted = 0,
    errors = 0,
    action_allowlist = {},
    players = setmetatable({}, { __mode = "k" }),
}
