[web]
    bind to = localhost

[directories]
    cache = /data/netdata/cache
    lib = /data/netdata/lib
    log = /data/netdata/log
    home = /data/netdata/lib

[logs]
    debug = journal
    daemon = journal
    collector = journal
    access = journal
    health = journal

[cloud]
    conversation log file = journal

[db]
    storage tiers = 3
    dbengine page cache size = 8GiB
    dbengine extent cache size = off
    dbengine tier 0 retention size = 4TiB
    dbengine tier 0 retention time = 1y
    dbengine tier 1 retention size = 2TiB
    dbengine tier 1 retention time = 5y
    dbengine tier 2 retention size = 1TiB
    dbengine tier 2 retention time = 10y

[health]
    in memory max health log entries = 100000
    health log retention = 1y
