journal:
  paths:
    - /data/netdata/log/otel/v1

cache:
  directory: /data/netdata/cache/otel-signal-viewer
  memory_capacity: 10000
  disk_capacity: "256GiB"
  block_size: "4MB"
  queue_capacity: 100

indexing:
  max_unique_values_per_field: 100000
  max_field_payload_size: 512
